# Generated by Django 2.2.6 on 2019-11-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=1)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='flores')),
            ],
        ),
    ]
