# Generated by Django 3.0 on 2019-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
