# Generated by Django 2.2.6 on 2019-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_auto_20191214_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
